image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

before_script:
  - docker info
  - apk add --no-cache docker-compose

build:
  stage: build
  script:
    - docker-compose -f smart/docker-compose.yml up -d --build
  artifacts:
    paths:
      - smart/
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Сборка завершена. Эксперты могут скачать артефакты или открыть адрес."

