version: '3.8'

services:
  logora:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./python:/app/python
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
