version: '3.8'

services:
  logora:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./db:/app/db
    environment:
      - DATABASE_URL=sqlite:///db/logora.sqlite
    command: /app/start.sh
