name: Build & Smoke Test Smart ЖКХ

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1) Залонить код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Настроить Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) Установить docker-compose v2
      - name: Install Docker Compose plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      # 4) Отладочный листинг
      - name: List files
        run: ls -R .

      # 5) Инициализировать базы через Makefile (если нужно)
      - name: Initialize databases
        run: make init_dbs

      # 6) Построить и запустить все сервисы
      - name: Build & start services
        run: docker compose up --build -d

      # 7) Дать сервисам 30 секунд на стартап
      - name: Wait for services startup
        run: |
          echo "Waiting for API to be healthy…"
          for i in $(seq 1 15); do
            if curl --fail http://localhost:5000/health; then
              echo "✅ API is healthy"
              break
            else
              echo "…not up yet, retrying"
              sleep 2
            fi
          done

      # 8) Проверить, что все контейнеры запущены
      - name: List running containers
        run: docker ps

      # 9) Smoke‑тесты: пробежаться по базовым эндпоинтам
      - name: Smoke test API endpoints
        run: |
          set -e
          curl --fail http://localhost:5000/            && echo "/ root OK"
          curl --fail http://localhost:5000/health      && echo "/health OK"
          curl --fail http://localhost:5001/api/payments && echo "Payment OK"
          curl --fail http://localhost:5002/health      && echo "Billing OK"
          curl --fail http://localhost:5003/api/accounts && echo "Account OK"
          curl --fail http://localhost:5004/health      && echo "Report OK"

      # 10) Остановить и удалить
      - name: Teardown
        if: always()
        run: docker compose down --volumes --remove-orphans
