name: Build & Deploy Frontend Smart ЖКХ

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      # 1) Залонить код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Настроить Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) Установить docker-compose-plugin
      - name: Install Docker Compose plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      # 4) Отладочный листинг
      - name: List files
        run: ls -R .

      # 5) Собрать только frontend сервис
      - name: Build frontend Docker image
        run: docker compose build frontend

      # 6) Запустить frontend контейнер
      - name: Run frontend container
        run: docker compose up -d frontend

      # 7) Проверка работы frontend
      - name: Smoke test frontend
        run: |
          echo "Waiting for frontend..."
          sleep 5  # Можно заменить на healthcheck при необходимости
          curl --fail http://localhost:3000 || (echo "Frontend is not responding!" && exit 1)

      # 8) Teardown
      - name: Teardown
        if: always()
        run: docker compose down --volumes --remove-orphans
